using BTCPayServer.Lightning;
using BTCPayServer.Plugins.Wavelength.Services;
using Microsoft.Extensions.DependencyInjection;
using NBitcoin;

namespace BTCPayServer.Plugins.Wavelength.Lightning;

/// <summary>
/// Resolves "type=wavelength;token=...;(extra waved flags)" connection strings to a per-store
/// WavelengthLightningClient. Unlike LND/CLN-style handlers, the connection string carries no
/// externally-meaningful address - waved is plugin-managed per store, so the token is just an
/// opaque lookup key into WavedProcessManager, resolved back to the real storeId via
/// WavedStoreTokenProtector rather than being the storeId itself (see that class's doc comment
/// for why - in short, a store's real ID is too easy to come by to double as authorization for
/// which waved instance a connection string is allowed to reach). Every other key (besides
/// "type"/"token") is passed through verbatim as a "--key value" waved flag - e.g.
/// "network=regtest" becomes "--network regtest" - except the handful WavedReservedFlags.Keys
/// owns, which are rejected here rather than silently dropped or silently overridden.
/// </summary>
public sealed class WavelengthLightningConnectionStringHandler(
    IServiceProvider serviceProvider, WavedStoreTokenProtector tokenProtector)
    : ILightningConnectionStringHandler
{
    public ILightningClient? Create(string connectionString, Network network, out string? error)
    {
        var kv = LightningConnectionStringHelper.ExtractValues(connectionString, out var type);
        if (type != "wavelength")
        {
            error = null;
            return null;
        }

        if (!kv.TryGetValue("token", out var token))
        {
            error = kv.ContainsKey("store-id")
                ? "The key 'store-id' is no longer used for wavelength connection strings - replace " +
                  "it with the token shown on this store's Lightning setup page."
                : "The key 'token' is required for wavelength connection strings - see this store's " +
                  "Lightning setup page for its own generated token.";
            return null;
        }

        if (!tokenProtector.TryUnprotect(token, out var storeId))
        {
            error = "This wavelength connection string's token is invalid, or was generated by a " +
                    "different BTCPay Server instance.";
            return null;
        }

        if (!TryParseExtraFlags(connectionString, out var extraFlags, out error))
            return null;

        // Not ActivatorUtilities.CreateInstance here on purpose: WavelengthLightningClient's
        // constructor now has two string parameters (storeId, token, in that order) - relying on
        // ActivatorUtilities' type-based positional matching to keep them in the right order is
        // exactly the kind of thing that fails silently (swapped values, not a compile error or
        // even necessarily a visible runtime error) rather than loudly. WavedProcessManager is
        // the only actual DI dependency here, so resolving it directly removes the ambiguity
        // entirely instead of just trusting it works out.
        var processManager = serviceProvider.GetRequiredService<WavedProcessManager>();
        return new WavelengthLightningClient(
            processManager, network, storeId, token, (IReadOnlyDictionary<string, string>)extraFlags);
    }

    /// <summary>
    /// Extracts the extra waved flags from a wavelength connection string ("type" and "token"
    /// stripped, WavedReservedFlags.Keys rejected) - the same parsing <see cref="Create"/> uses,
    /// exposed so other call sites (e.g. the Advanced page's "Restart waved" action, which needs
    /// to re-derive flags from the store's current live connection string rather than whatever
    /// was last persisted) don't have to duplicate it.
    /// </summary>
    public static bool TryParseExtraFlags(string connectionString, out Dictionary<string, string> extraFlags, out string? error)
    {
        extraFlags = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase);
        var kv = LightningConnectionStringHelper.ExtractValues(connectionString, out _);
        foreach (var (key, value) in kv)
        {
            if (key is "type" or "token")
                continue;

            if (WavedReservedFlags.Keys.Contains(key))
            {
                error = $"The key '{key}' is managed by the plugin and cannot be set in a wavelength " +
                        "connection string. Remove it - everything else waved accepts is passed through.";
                return false;
            }

            extraFlags[key] = value;
        }

        error = null;
        return true;
    }
}
